import type { MetadataRoute } from 'next';

// Web app manifest (installable PWA basics). Icons are the logo-derived tiles
// generated by scripts/generate-brand-assets.mjs: a 192 and 512 "any" plus a 512
// maskable with a safe zone. The favicon and apple-touch icon are wired from the
// app/ filename conventions (favicon.ico, icon.png, apple-icon.png).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'CampusOS',
    short_name: 'CampusOS',
    description: 'Live timetables and campus tools for universities.',
    start_url: '/',
    display: 'standalone',
    background_color: '#000000',
    theme_color: '#000000',
    icons: [
      { src: '/icon-192.png', type: 'image/png', sizes: '192x192', purpose: 'any' },
      { src: '/icon-512.png', type: 'image/png', sizes: '512x512', purpose: 'any' },
      { src: '/icon-maskable-512.png', type: 'image/png', sizes: '512x512', purpose: 'maskable' },
    ],
  };
}
