import { expect, test } from '@playwright/test';
import { pageAs } from './support/sessions';

/**
 * A photo posted with a Lost & Found item round-trips through the media pipeline
 * and serves back from /media. This pins two things a browser depends on: the
 * upload endpoint accepts a real image (magic-byte + sharp), and /media is served
 * (not swallowed by the tenant rewrite). The upload is driven through the API so a
 * failure surfaces its status and body here rather than being swallowed by the
 * post form's best-effort photo loop.
 */

const ourOrigin = () => ({ origin: String(test.info().project.use.baseURL) });

// A 16x16 PNG generated by sharp itself, so the pipeline is guaranteed to decode
// it (a hand-picked 1x1 tripped sharp's decoder). The bytes must be a genuine
// image; a fake buffer would fail the magic-byte sniff or the decode.
const SAMPLE_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAGElEQVR4nGM4oaFBEmIY1aAxquHEcNUAAHwzGBBnUymTAAAAAElFTkSuQmCC',
  'base64',
);

test('a member posts a lost-found item with a photo that serves from /media', async ({
  browser,
}) => {
  const page = await pageAs(browser, 'member');

  // Create the item (verified member). page.request carries the session cookie.
  const created = await page.request.post('/api/lost-found/items', {
    headers: { ...ourOrigin(), 'content-type': 'application/json' },
    data: { tenant: 'lgu', kind: 'lost', title: 'Lost umbrella e2e', category: 'other' },
  });
  const createdBody = await created.text();
  expect(created.ok(), createdBody).toBeTruthy();
  const { id } = JSON.parse(createdBody) as { id: string };

  // Upload a real image through the pipeline; assert it succeeds. If MEDIA_DATA_DIR
  // or the pipeline is wrong, the status and body show up in this assertion.
  const uploaded = await page.request.post(`/api/lost-found/items/${id}/photos`, {
    headers: ourOrigin(),
    multipart: {
      tenant: 'lgu',
      file: { name: 'sample.png', mimeType: 'image/png', buffer: SAMPLE_PNG },
    },
  });
  expect(uploaded.ok(), await uploaded.text()).toBeTruthy();

  // The item page renders the photo from /media, and the URL actually serves.
  await page.goto(`/u/lgu/lost-found/${id}`);
  const img = page.locator('img[src^="/media/"]').first();
  await expect(img).toBeVisible();
  const src = await img.getAttribute('src');
  expect(src).toBeTruthy();
  const served = await page.request.get(src!);
  expect(served.status()).toBe(200);
  expect(served.headers()['content-type'] ?? '').toContain('image/');
});
